In [1]:
import numpy as np
import pandas as pd

In [2]:
exams = pd.read_csv('data-2072-2024-04-15.csv', sep=';')
exams = exams.drop(index=0)
exams = exams.drop("Unnamed: 8", axis=1)
exams['EDU_NAME'] = exams['EDU_NAME'].str.lower().str.strip().str.replace('«', '').str.replace('»', '') \
.str.replace('  ', ' ')
exams.head()

,ID,EDU_NAME,global_id,YEAR,AdmArea,District,PASSES_OVER_220,PASSER_UNDER_160
1,8236,государственное бюджетное общеобразовательное ...,797946035,2016-2017,Восточный административный округ,район Богородское,5,19
2,8237,государственное казенное общеобразовательное у...,797949150,2016-2017,Восточный административный округ,район Богородское,14,47
3,8238,государственное казенное общеобразовательное у...,797949275,2016-2017,Восточный административный округ,район Вешняки,0,1
4,8239,частное учреждение общеобразовательная организ...,797949425,2016-2017,Восточный административный округ,район Вешняки,0,6
5,8240,автономная некоммерческая организация средняя ...,797949570,2016-2017,Восточный административный округ,район Восточное Измайлово,1,5

In [3]:
schools = pd.read_csv('data-2263-2024-07-08.csv', sep=';')
schools = schools.drop(index=0)
schools = schools.drop("Unnamed: 26", axis=1)
schools['FullName'] = schools['FullName'].str.lower().str.strip().str.replace('«', '').str.replace('»', '') \
.str.replace('  ', ' ')
schools.head()

,OrgType,ReorganizationStatus,IDEKIS,FullName,ShortName,Number,INN,KPP,OGRN,LegalOrganization,...,WebSite,EducationPrograms,EducationalServices,LicensingAndAccreditation,SupplementaryClassesAndGroups,NumberofStudentsInOO,TheContingentOfPreschoolersStudyingOO,global_id,geoData,geodata_center
1,прочее,действующее,14500,государственное автономное учреждение города м...,ГАУ Медиацентр,NaN,7718924940,771801001,1137746210161,автономное,...,shkolamoskva.ru,NaN,nested data,nested data,nested data,nested data,nested data,1139421628,"{coordinates=[[[37.704597369, 55.80046703], [3...",NaN
2,организация дополнительного профессионального ...,действующее,14494,государственное автономное образовательное учр...,ГАОУ ДПО «Корпоративный университет»,NaN,7714239823,771301001,1027700566761,автономное,...,corp-univer.ru,Профессиональное образование | высшее образова...,nested data,nested data,nested data,nested data,nested data,2386776971,"{coordinates=[[[[37.539544671, 55.799821354], ...",NaN
3,организация дополнительного профессионального ...,действующее,14506,государственное автономное образовательное учр...,ГАОУ ДПО МЦРПО,NaN,7707329480,772201001,1057707018192,автономное,...,mcrpo.ru,Дополнительное образование | дополнительное об...,nested data,nested data,nested data,nested data,nested data,2645605456,"{coordinates=[[[[37.711001873, 55.762921204], ...",NaN
4,организация дополнительного профессионального ...,действующее,14605,государственное бюджетное образовательное учре...,ГБОУ ДПО МЦВП,NaN,7723029678,772301001,1027739293944,бюджетное,...,mcvp.ru,Дополнительное образование | дополнительное об...,nested data,nested data,nested data,nested data,nested data,2645605458,"{coordinates=[[[[37.65201246, 55.742196123], [...",NaN
5,организация дополнительного профессионального ...,действующее,13070,государственное автономное образовательное учр...,ГАОУ ДПО ЦПМ,NaN,7725618950,770401001,1077761137222,автономное,...,cpm.dogm.mos.ru,Дополнительное образование | дополнительное об...,nested data,nested data,nested data,nested data,nested data,2654965921,"{coordinates=[[[[37.56961301, 55.671061893], [...",NaN

In [4]:
ecology = pd.read_csv('data-2457-2024-05-03.csv', sep=';')
ecology = ecology.drop(index=0)
ecology = ecology.drop("Unnamed: 11", axis=1)
ecology.head()

,global_id,ID,Date,AdmArea,District,Longitude_WGS84,Latitude_WGS84,Location,Results,geoData,geodata_center
1,272399481,103,11.03.2016,Юго-Восточный административный округ,район Марьино,37.746472,55.659195,"улица Перерва, дом 39",Содержание загрязняющих веществ в атмосферном ...,"{coordinates=[37.746472, 55.659195], type=Point}","{coordinates=[37.746472, 55.659195], type=Point}"
2,272399482,104,10.03.2016,Центральный административный округ,Красносельский район,37.632260,55.762905,"Милютинский переулок, дом 12",Содержание загрязняющих веществ в атмосферном ...,"{coordinates=[37.63226, 55.762905], type=Point}","{coordinates=[37.63226, 55.762905], type=Point}"
3,272399483,105,11.03.2016,Северо-Западный административный округ,район Митино,37.357923,55.829820,"улица Рословка, дом 6, корпус 2",Содержание загрязняющих веществ в атмосферном ...,"{coordinates=[37.357923, 55.82982], type=Point}","{coordinates=[37.357923, 55.82982], type=Point}"
4,272399484,106,11.03.2016,Северо-Западный административный округ,район Щукино,37.455031,55.795514,"Живописная улица, дом 40",Содержание загрязняющих веществ в атмосферном ...,"{coordinates=[37.455031, 55.795514], type=Point}","{coordinates=[37.455031, 55.795514], type=Point}"
5,272399485,113,14.03.2016,Зеленоградский административный округ,район Крюково,37.189678,55.964282,"город Зеленоград, корпус 2308А",Содержание загрязняющих веществ в атмосферном ...,"{coordinates=[37.189678, 55.964282], type=Point}","{coordinates=[37.189678, 55.964282], type=Point}"

In [5]:
exams_gps = exams.merge(schools[['FullName', 'geoData']], left_on='EDU_NAME', right_on='FullName', how='left')
exams_gps.head()

,ID,EDU_NAME,global_id,YEAR,AdmArea,District,PASSES_OVER_220,PASSER_UNDER_160,FullName,geoData
0,8236,государственное бюджетное общеобразовательное ...,797946035,2016-2017,Восточный административный округ,район Богородское,5,19,NaN,NaN
1,8237,государственное казенное общеобразовательное у...,797949150,2016-2017,Восточный административный округ,район Богородское,14,47,государственное казенное общеобразовательное у...,"{coordinates=[[[[37.710083127, 55.825085846], ..."
2,8238,государственное казенное общеобразовательное у...,797949275,2016-2017,Восточный административный округ,район Вешняки,0,1,государственное казенное общеобразовательное у...,"{coordinates=[[[[37.807984129, 55.726758653], ..."
3,8239,частное учреждение общеобразовательная организ...,797949425,2016-2017,Восточный административный округ,район Вешняки,0,6,NaN,NaN
4,8240,автономная некоммерческая организация средняя ...,797949570,2016-2017,Восточный административный округ,район Восточное Измайлово,1,5,NaN,NaN

In [6]:
exams_gps['geoData'].isna().sum()

1586

In [7]:
exams_gps['geoData'].notna().sum()

3298

In [8]:
filtered_edu_names = exams_gps.loc[exams_gps['geoData'].isna(), 'EDU_NAME'].copy()
pd.set_option('display.max_colwidth', None)
filtered_edu_names

0                                                                                                                             государственное бюджетное общеобразовательное учреждение города москвы школа № 390 имени генерала п.и. батова
3                                                                                                                                             частное учреждение общеобразовательная организация московская интернациональная школа планета
4                                                                                                                                                           автономная некоммерческая организация средняя общеобразовательная школа колибри
6                                                                                                                                                            государственное бюджетное образовательное учреждение города москвы школа № 922
7                                                                                                                                           государственное бюджетное общеобразовательное учреждение города москвы центр образования № 1483
                                                                                                                       ...
4866                                                                                                                                          автономная некоммерческая организация православная общеобразовательная школа-пансион плесково
4869    федеральное государственное автономное образовательное учреждение высшего образования национальный исследовательский университет высшая школа экономики. лицей национального исследовательского университета высшая школа экономики
4872                                                                                                                                                      общеобразовательная автономная некоммерческая организация елизаветинская гимназия
4878                                                                                                                                         частное учреждение средняя общеобразовательная школа славянско-англо-американская школа марина
4880                                                                                                                                                      общеобразовательная автономная некоммерческая организация школа права и экономики
Name: EDU_NAME, Length: 1586, dtype: object